version: 2.1
jobs:
  Test:
    docker:
      - image: aimvector/python:1.0.1
    steps:
      - checkout
      - run: go test -v ./...
  Build:
    docker:
      - image: aimvector/python:1.0.1
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go build -o example-app
      - persist_to_workspace:
          root: .
          paths:
            - ./example-app
            - ./deployment.yaml
  Publish:
    docker:
      - image: aimvector/python:1.0.1
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: /tmp/workspace
      - run: |
          cp /tmp/workspace/exampleapp .
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t alexanderh12/cicrleci-exampleapp:$TAG .
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push alexanderh12/cicrleci-exampleapp:$TAG
  GenerateYAML:
    docker:
      - image: aimvector/python:1.0.1
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run : |
          TAG=0.1.$CIRCLE_PREVIOUS_BUILD_NUM
          git clone https://github.com/AlexanderHuybrichs/ArgoCD /tmp/CircleCI-Webapp-CD
          cd /tmp/CircleCI-Webapp-CD
          cp /tmp/workspace/deployment.yaml .
          sed -i 's/\(cicrleci-exampleapp\)\(.*\)/\1:'$TAG'/' ./deployment.yaml
          git config credential.helper 'cache --timeout=120'
          git config user.email "Alexander.Huybrichs@student.pxl.be"
          git config user.name "AlexanderHuybrichs"
          git add .
          git commit -m "Update via CircleCI"
          # Push quietly to prevent showing the token in log
          git push -q https://$GITHUB_PERSONAL_TOKEN@github.com/AlexanderHuybrichs/ArgoCD.git main
workflows:
  version: 2
  Test-Build-Publish:
    jobs:
      - Test
      - Build:
          requires:
            - Test
      - Publish:
          requires:
            - Build
      - GenerateYAML:
          requires:
            - Publish     
